language: java
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  slack:
    secure: iCnARnX44nSGcS8VkvsWbMJDHAnCHCvKLtScHlG8n9oDoYXIG3JCZ557eYJF78KbeTGFQiTW2kDi4/DwnTYiZSmPWveEkeNYDxwF7JlX89yeaepbJbfakY+CMjVxz8NdDbHTHl2eRoqoVg8rXqsudjA7rTzjCuI6RF/oe2fhWbcWUe4cdxOPwEl+STovPc79euLoC2AHwrS98RE8aki7D3bhhy8FYeiUbLdTgHk5XFPzRQohTFLJHkApU+uGuYsuh1Aw8PDhXuFmXsbbg2u87o58PKjSdg92dkumDWaxZ/F5MEbui1ths4ygaksFvXWTvWpRbdN4iDqYdu9B0p+1g3W972qhpwafOVayg0XaInrKmwiaCxOHjfCLsJNHxHs2Y2RO0FWGdJ21BPMuMwn9IP3vMpZ8sHkCwH8VaMLjhYNHvjFloBgPbCqItrd5XjObx/DevQ9i6WjwNzvL0FAa+NBPbrzTXx79xqmDzDI2hY52DcKLuCOwUNWbSk4FBFC/DgDGP4uJF5ps97fUoiQa3/pL6wStpa3nUxwLDCaZNQT9AfMi3rhIbM9aBFi+q/+vxfSZgFsZBIJmTJZ2jc2Rf3ny4s/PGN62XlIuqoZmB1qLVQz7aTijBHNFYtUE0Fc0BkoRv75lEL3feL3EEd17xJnzMJbV1Hh80sPXoiFI+ak=
  email:
  - anthony.denecheau@gmail.com
  on_success: always
  on_failure: always
env:
  global:
  - secure: JlBvHk+9Pez/5GzdYLy61E3msCM6i/iVG5x3szS1WGhEPMY1Zc5rq+4tGmC/NW7Ltoh/EKF/qAsQUKVRaqqPB41HfpsNHSa8iQDE2r1yO2EFMMiAoKBdNJ9ysMNCOvwBvrr8W1nouE+9IYQDdTh8Oap8lIfSqV10F08iSWsB0MmwL21UUTYGuhXX+9nHnQw0o+NMURR2IJXOPhZsjmfbhmFf7ivyZzvhBCOQepP9qTa+WHpJlFPHi0TXZotHWyfE85K9vIhYsQ0xG5Lxqr7qvZlg3Eyrtz1NNwwXONUq++3fKAla7TWx5Vj9pjA6oZK2+DagFXtftUs6xXfwIPFmmN9CNy0ZFeR2iugbLpuyqCMcD/hwXO/nEqVs58m5t8kbr93I8FBNOAO2C0w/rv0W1i/5QLYkXyx7YZNDUVD88BFqQEUzq4QC7mfRkaKOI6+b7D9p85QfcHaLllhG0h0A+jbeTujCmGO/DHWoOByT8O/fSC8ntlHqVuLnEelMMjJOqG/IwVuAJGpbO2orC6VZPWSEgSoHveHw9/2LRntoqfpnBy4vquierrhKz4UDGt66OC/1vXB31uVSF5nj8HFxTYPt1Qi6M5+KEoUe4tYYE34EYVlceob5zb6NwzvcRKE6HhaGMAaMp5LDsrAKWWiW6OGNy4RlWeB69fUDUT0YUxA=
  - secure: US72jppB8QPoZwMlNPy5kR4NqfqVfOGNnY6THJAAHVBOiFJLr/cKC1lfg+jgwXi1lk7oGyIIYvmV2z/HUdajpzHMCozzYLmUo+VIB1qCAZTNMC4f2+xOqwHz6K8xfmxyrXv6//Nh1e12pjaJZRTPdEW95W8pwWsi+4Tqa8Xx1KEbOlMfXdc2g4LKnb4oJOASVfL1V5RR87NuhovxvwH6TflxqJsBzxf+mFN6YYOTpGcZscJLCv7RFj1VqhhqT7xrJxQm9CMZCcjo4kQS8XiyDZwDnUqjIt6oOvp3WxvEyPAuGa//v56bUSn0NquVkeFJ+GWFjppgBXPHWsE4YuP1IOVSt2biTGkRuWf/pN+Oez/Wmy2lawwC5y73roDrIHASm6wn9bXN8OKDbs0xhcnmfcTTQKF36j2/0wtxcKsla8cj2AqYfLy96++SSIDPLfjY1FncCFNgPmz9egQaVBwHqxmxEm+pc52IKrc9PTPeIiyW6tXLPzKudG/oKfGATDas56vqHi+S/pjHgT7yXwAglujte/T6b08l7qSt0oFNb5rRSlX7omMYEiiYF3XdhAeBeK0ly47bbU79/Lg1GeIqECqyxPN6EzfnVbMI1tKQjTx2xL1c3ZAshnPhfYV6F3fL5s5gzmsOAdxtoBLu6uL92vDBYZ7UCDWax0QF48g+65c=
  matrix:
  - SCC_DOCKER_IMAGE=anthonydenecheau/scc-daemon-service:version1.0
script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- mvn clean package docker:build
- docker push $SCC_DOCKER_IMAGE
