spring:
  zipkin:
    baseUrl:  http://localhost:9411

eureka:
  instance:
    preferIpAddress: true
    lease-expiration-duration-in-seconds: 30 
    lease-renewal-interval-in-seconds: 10
#    statusPageUrlPath: ${management.contextPath}/info      
#    healthCheckUrlPath: ${management.contextPath}/health
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true  
        
#management:
#  contextPath: /admin     
     
#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.scc: DEBUG      