#Default port is 8082
server:
  port: 8082
  
spring:
#Kafka settings
  cloud:
    stream:
      bindings:
        output:
            destination:  dogChangeTopic
            content-type: application/json
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost
          autoCreateTopics: true
  
#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.scc: DEBUG      
    org.apache.kafka: WARN
